### PR TITLE
feat: support changing resource priority

### PR DESCRIPTION
**Pull request by misterupkeep**
This pull request also is the first to use our fork of stanza: [@bonfire-xmpp/verse](https://github.com/bonfire-xmpp/verse), which was semi-necessary for resource priority setting (it offloads the responsibility of keeping track of it to the library -- partly)

The only thing that needs to be reviewed is the UI; I'll check the issues present in **verse** and merge after UI stuff has settled

image
image
image
image
image

### CODE REVIEW

**Review by 00drip — COMMENTED** [review]
It looks fine for the most part, but I really don't like the glow/border around the spinner. I would use a very thin solid border or none at all if it fit.

**Comment by misterupkeep** [comment]
> It looks fine for the most part, but I really don't like the glow/border around the spinner. I would use a very thin solid border or none at all if it fit.

It's `2px` as it stands, and the border between the buttons is `1px`. Here is an image with all borders set to `1px`
image
Honestly, I'm torn.

**Comment by 00drip** [comment]
That looks way nicer IMO. It shouldn't look more eye-catching than any other piece of that menu.

**Comment by misterupkeep** [comment]
It turns out that any and all issues present in **verse** are present in the latest tag on upstream, meaning it's not a regression on our part (hopefully it doesn't break anything).

**Pull request merged**
